font_family JetBrainsMono Nerd Font
font_size 12


hide_window_decorations yes
window_padding_width 4
dynamic_background_opacity yes

# Disable Linux/X11-style primary-selection paste on middle click.
mouse_map middle release ungrabbed
mouse_map shift+middle release ungrabbed,grabbed
mouse_map shift+middle press grabbed discard_event

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME

include kitty-mode.conf
