[tools]
android-sdk = "latest"
bun = "latest"
go = "latest"
gradle = "9"
herdr = "latest"
java = "25.0.2"
jbang = "latest"
maven = "3"
node = "lts"
pnpm = "latest"
uv = "latest"
"github:spicetify/cli" = "latest"
